spring.application.name=CodeNova-SOU

server.port=${PORT:8080}

# JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Database
spring.datasource.url=jdbc:mysql://codenova-jogeshchaudhary555-cbce.d.aivencloud.com:16237/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_u20lE-8UREnwnuWyYB8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Multipart
server.tomcat.max-part-count=30
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB